# Generated by Django 3.2.21 on 2023-12-18 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_Number', models.DecimalField(decimal_places=0, max_digits=10)),
                ('patient_Name', models.CharField(max_length=256)),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1)),
                ('address', models.CharField(max_length=256)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=10)),
                ('SSN', models.DecimalField(decimal_places=0, max_digits=9)),
                ('Blood_Type', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB+', 'AB+')], max_length=3)),
                ('Blood_Sugar', models.DecimalField(decimal_places=3, max_digits=5)),
                ('HDL', models.DecimalField(decimal_places=0, max_digits=3)),
                ('LDL', models.DecimalField(decimal_places=0, max_digits=3)),
                ('Triglycerides', models.DecimalField(decimal_places=0, max_digits=3)),
                ('CR', models.DecimalField(decimal_places=2, max_digits=3)),
                ('Heart_Disease_Risk', models.CharField(max_length=8)),
                ('illness_Desc', models.TextField()),
                ('illness_Code_1', models.DecimalField(decimal_places=0, max_digits=3)),
                ('illness_Code_2', models.DecimalField(decimal_places=0, max_digits=3)),
                ('illness_Code_3', models.DecimalField(decimal_places=0, max_digits=3)),
                ('illness_Code_4', models.DecimalField(decimal_places=0, max_digits=3)),
                ('illness_Code_5', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.DecimalField(decimal_places=0, max_digits=4)),
                ('room_avail_start', models.DateTimeField()),
                ('room_avail_end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_Number', models.DecimalField(decimal_places=0, max_digits=6)),
                ('employee_Name', models.CharField(max_length=256)),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1)),
                ('address', models.CharField(max_length=256)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=10)),
                ('SSN', models.DecimalField(decimal_places=0, max_digits=9)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee_type', models.CharField(choices=[('DR', 'Doctor'), ('G', 'Surgeon'), ('N', 'Nurse'), ('ST', 'Staff')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_Number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.staff')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.room')),
            ],
        ),
        migrations.CreateModel(
            name='jobShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_start', models.DateTimeField()),
                ('shift_end', models.DateTimeField()),
                ('employment_Number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.staff')),
            ],
        ),
        migrations.CreateModel(
            name='inpatientCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_Number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.staff')),
                ('patient_Number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.room')),
            ],
        ),
        migrations.CreateModel(
            name='doctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_schedule_start', models.DateTimeField()),
                ('doctor_schedule_end', models.DateTimeField()),
                ('employment_Number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.staff')),
                ('patient_Number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultaion_Number', models.DecimalField(decimal_places=0, max_digits=9)),
                ('start_Time', models.DateField()),
                ('end_Time', models.DateField()),
                ('employment_Number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.staff')),
            ],
        ),
    ]
