# Generated by Django 3.2.21 on 2023-12-18 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='end_Time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='start_Time',
            field=models.DateTimeField(),
        ),
    ]
