# Generated by Django 3.2.21 on 2023-12-18 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20231218_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgery',
            name='patient_Number',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
            preserve_default=False,
        ),
    ]
